
FILE FREEFORM = 11D58956-AA91-435F-95FA-5C56FDB05AF2 {
    SECTION UI = "cannot_be_checked_image.bmp"
    SECTION RAW = RawFiles/cannot_be_checked_image.bmp
}


FILE FREEFORM = 4611A922-C157-4DFD-9EF7-EC408F464C7F {
    SECTION UI = "device_corrupt_image.bmp"
    SECTION RAW = RawFiles/device_corrupt_image.bmp
}


FILE FREEFORM = 1D334DA6-3815-495F-9608-8AD85D6AF3B8 {
    SECTION UI = "os_not_found_image.bmp"
    SECTION RAW = RawFiles/os_not_found_image.bmp
}


FILE FREEFORM = EF3D719D-C2AE-497A-83CA-EF69FE777242 {
    SECTION UI = "different_os_image.bmp"
    SECTION RAW = RawFiles/different_os_image.bmp
}


FILE FREEFORM = AAC70040-34F2-4912-8B8A-A8EFB62E267A {
    SECTION UI = "orange_visit_image.bmp"
    SECTION RAW = RawFiles/orange_visit_image.bmp
}


FILE FREEFORM = 787F6C65-25E0-4EF0-8082-FB29FD9605A9 {
    SECTION UI = "unlock_confirm_button.bmp"
    SECTION RAW = RawFiles/unlock_confirm_button.bmp
}


FILE FREEFORM = A1424733-433F-4A65-AE5A-CCC7AA8752B2 {
    SECTION UI = "unlock_cancel_button.bmp"
    SECTION RAW = RawFiles/unlock_cancel_button.bmp
}


FILE FREEFORM = 55820B37-304C-40AE-B25B-5EC6719C9F06 {
    SECTION UI = "lock_confirm_button.bmp"
    SECTION RAW = RawFiles/lock_confirm_button.bmp
}


FILE FREEFORM = 0151CF76-0180-4A3D-BCDC-DDC3432734F4 {
    SECTION UI = "lock_cancel_button.bmp"
    SECTION RAW = RawFiles/lock_cancel_button.bmp
}


FILE FREEFORM = 7578308A-FB55-42DD-A848-CC4D74FCA42B {
    SECTION UI = "fastboot_intro.bmp"
    SECTION RAW = RawFiles/fastboot_intro.bmp
}


FILE FREEFORM = C94F538F-D9BA-4B95-899F-6E3F891F0EC6 {
    SECTION UI = "fastboot_instructions.bmp"
    SECTION RAW = RawFiles/fastboot_instructions.bmp
}


FILE FREEFORM = 2212A94E-07B1-49F9-A1A2-321BCA66A65C {
    SECTION UI = "fastboot_instructions_180.bmp"
    SECTION RAW = RawFiles/fastboot_instructions_180.bmp
}


FILE FREEFORM = 7DA147A7-6612-4060-A57C-82B248C09A17 {
    SECTION UI = "device_info_button.bmp"
    SECTION RAW = RawFiles/device_info_button.bmp
}


FILE FREEFORM = EC1C7DE4-1DA5-4563-819E-BE9FF174E872 {
    SECTION UI = "start_button.bmp"
    SECTION RAW = RawFiles/start_button.bmp
}


FILE FREEFORM = 94317306-1378-4461-B698-4B44A06BD9F3 {
    SECTION UI = "reboot_bootloader_button.bmp"
    SECTION RAW = RawFiles/reboot_bootloader_button.bmp
}


FILE FREEFORM = 423169B5-22F3-4017-8EAB-710B51561850 {
    SECTION UI = "recovery_mode_button.bmp"
    SECTION RAW = RawFiles/recovery_mode_button.bmp
}


FILE FREEFORM = 7D07103E-1D76-4706-A84F-5AD6F7AA6EDC {
    SECTION UI = "poweroff_button.bmp"
    SECTION RAW = RawFiles/poweroff_button.bmp
}


FILE FREEFORM = DAA2079F-A31D-40FA-96D0-1E0134805C20 {
    SECTION UI = "barcode_button.bmp"
    SECTION RAW = RawFiles/barcode_button.bmp
}


FILE FREEFORM = E90032C1-671B-4283-A9A3-BD225F3B3BCD {
    SECTION UI = "Roboto-Regular.ttf"
    SECTION RAW = RawFiles/Roboto-Regular.ttf
}

INF QcomModulePkg/Application/LinuxLoader/LinuxLoader.inf
