
FILE FREEFORM = E2EA5A4F-98BD-4203-AB49-399505DDFB7D {
    SECTION UI = "tsens_thermal_symbol.bmp"
    SECTION RAW = RawFiles/tsens_thermal_symbol.bmp
}


FILE FREEFORM = C72FB1A9-5527-4E13-BAC4-F671D0330145 {
    SECTION UI = "tsens_thermal_err_symbol.bmp"
    SECTION RAW = RawFiles/tsens_thermal_err_symbol.bmp
}


FILE FREEFORM = B0F8D1BE-5353-4812-B1F6-07E7768204CC {
    SECTION UI = "battery_symbol_DebugBoot.bmp"
    SECTION RAW = RawFiles/battery_symbol_DebugBoot.bmp
}


FILE FREEFORM = F9E8F683-E065-4E09-B4F9-0230D7CECD08 {
    SECTION UI = "battery_symbol_DebugStay.bmp"
    SECTION RAW = RawFiles/battery_symbol_DebugStay.bmp
}


FILE FREEFORM = EAA0F50A-0B51-422D-87DE-10C2696552FA {
    SECTION UI = "high_temp.bmp"
    SECTION RAW = RawFiles/high_temp.bmp
}


FILE FREEFORM = 8B86CD38-C772-4FCF-85AA-345B2B3C1AB4 {
    SECTION UI = "battery_symbol_LowBatteryCharging.bmp"
    SECTION RAW = RawFiles/battery_symbol_LowBatteryCharging.bmp
}


FILE FREEFORM = 03DED53E-BECD-428F-9F79-5ABA64C58445 {
    SECTION UI = "battery_symbol_Nocharger.bmp"
    SECTION RAW = RawFiles/battery_symbol_Nocharger.bmp
}


FILE FREEFORM = 5FD8A447-12B3-BEB4-F3A0-E94A8DD3625D {
    SECTION UI = "battery_symbol_Nocharger_small.bmp"
    SECTION RAW = RawFiles/battery_symbol_Nocharger_small.bmp
}


FILE FREEFORM = 77FBE2DE-6D2D-B0DF-482C-CE51C3D950E7 {
    SECTION UI = "clock_colon.bmp"
    SECTION RAW = RawFiles/clock_colon.bmp
}


FILE FREEFORM = 159D4D9E-99E3-398D-B544-DC6B662597ED {
    SECTION UI = "clock_0.bmp"
    SECTION RAW = RawFiles/clock_0.bmp
}


FILE FREEFORM = A60D3AAB-8DD7-22A1-5B44-69D93BA8EAC0 {
    SECTION UI = "clock_1.bmp"
    SECTION RAW = RawFiles/clock_1.bmp
}


FILE FREEFORM = 5CEF035B-A39E-33AE-861F-16FFF44B7E4A {
    SECTION UI = "clock_2.bmp"
    SECTION RAW = RawFiles/clock_2.bmp
}


FILE FREEFORM = D119B8CF-61A6-2FA6-A665-F25A9B63473A {
    SECTION UI = "clock_3.bmp"
    SECTION RAW = RawFiles/clock_3.bmp
}


FILE FREEFORM = 3AC697FD-D847-5110-4B5F-36EFAD8F1550 {
    SECTION UI = "clock_4.bmp"
    SECTION RAW = RawFiles/clock_4.bmp
}


FILE FREEFORM = 093D2BB7-2CD4-3A44-12D5-94D71231A78A {
    SECTION UI = "clock_5.bmp"
    SECTION RAW = RawFiles/clock_5.bmp
}


FILE FREEFORM = 6655F773-0696-6A9A-FDDF-D76EF024906A {
    SECTION UI = "clock_6.bmp"
    SECTION RAW = RawFiles/clock_6.bmp
}


FILE FREEFORM = 435D4BEB-EEA1-4D8F-5AEB-D556DAEED120 {
    SECTION UI = "clock_7.bmp"
    SECTION RAW = RawFiles/clock_7.bmp
}


FILE FREEFORM = 54E63F4B-1A92-DBED-472F-D168595C149D {
    SECTION UI = "clock_8.bmp"
    SECTION RAW = RawFiles/clock_8.bmp
}


FILE FREEFORM = 9761FC4C-8194-A437-1A94-3B0F417CE032 {
    SECTION UI = "clock_9.bmp"
    SECTION RAW = RawFiles/clock_9.bmp
}

