INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
INF QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
INF QcomPkg/Drivers/TzDxe/ScmDxeLA.inf
INF QcomPkg/Drivers/TzDxe/TzDxeLA.inf
INF QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/RscRtDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SCHandlerRtDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF QcomPkg/Drivers/FontDxe/FontDxe.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/VcsDxe/VcsDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
INF QcomPkg/Drivers/FuseInfoDxe/FuseInfoDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/MinidumpTADxe/MinidumpTADxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
INF QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLA.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/QcomMpmTimerDxe/QcomMpmTimerDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/HashDxe/HashDxe.inf
INF QcomPkg/Drivers/CipherDxe/CipherDxe.inf
INF QcomPkg/Drivers/MacDxe/MacDxe.inf
INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/QcomBds/QcomBds.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Application/QcomChargerApp/QcomChargerApp.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
    SECTION UI = "BDS_Menu.cfg"
    SECTION RAW = RawFiles/BDS_Menu.cfg
}


FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
    SECTION UI = "Glogo.bmp"
    SECTION RAW = RawFiles/Glogo.bmp
}


FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030790 {
    SECTION UI = "splash.bmp"
    SECTION RAW = RawFiles/splash.bmp
}


FILE FREEFORM = 0D0D6B72-21D1-4249-8C09-9EABE9C198F7 {
    SECTION UI = "Fijit_symbol.bmp"
    SECTION RAW = RawFiles/Fijit_symbol.bmp
}


FILE FREEFORM = 02A7D6B7-12D1-4255-8C09-9EABE24198F7 {
    SECTION UI = "Color_Glogo_456.bmp"
    SECTION RAW = RawFiles/Color_Glogo_456.bmp
}


FILE FREEFORM = 77D6B723-2441-6891-1209-EA9BE9C19812 {
    SECTION UI = "Color_Glogo_408.bmp"
    SECTION RAW = RawFiles/Color_Glogo_408.bmp
}


FILE FREEFORM = 77A064F4-CF79-4DE6-9337-9304D4FAFCF9 {
    SECTION UI = "Panel_sim_panel_cmd.xml"
    SECTION RAW = RawFiles/Panel_sim_panel_cmd.xml
}


FILE FREEFORM = A9E001FA-7578-401B-B3D6-5F3337997877 {
    SECTION UI = "Panel_truly_rm69090_amoled_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_rm69090_amoled_cmd.xml
}


FILE FREEFORM = 940B76D7-C1F5-4C8F-8A90-3014D12CC335 {
    SECTION UI = "Panel_truly_rm6d030_amoled_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_rm6d030_amoled_cmd.xml
}


FILE FREEFORM = B77A50A1-5838-4D40-9BA4-89DC4D40638D {
    SECTION UI = "Panel_boe_amoled_wf012fbm_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wf012fbm_cmd.xml
}


FILE FREEFORM = D4255A49-A35D-4115-918E-BD526A914898 {
    SECTION UI = "Panel_boe_amoled_rm690c0_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_rm690c0_cmd.xml
}


FILE FREEFORM = 0BE86199-82D9-4523-B934-BFCE6C85C6B0 {
    SECTION UI = "Panel_sdc_amoled_amb120dd01_evt1_cmd.xml"
    SECTION RAW = RawFiles/Panel_sdc_amoled_amb120dd01_evt1_cmd.xml
}


FILE FREEFORM = F0E89CE2-D176-44FF-851F-39A9FFFE7AA3 {
    SECTION UI = "Panel_sdc_amoled_amb120dd01_cmd.xml"
    SECTION RAW = RawFiles/Panel_sdc_amoled_amb120dd01_cmd.xml
}


FILE FREEFORM = 491EB004-6900-6811-5BA8-E22CFF56C9CE {
    SECTION UI = "Panel_vnx_amoled_rm690c0_cmd.xml"
    SECTION RAW = RawFiles/Panel_vnx_amoled_rm690c0_cmd.xml
}


FILE FREEFORM = AC7C0AE3-EAFC-4500-9DE2-3054A56EBB4C {
    SECTION UI = "Panel_boe_amoled_wj013pgm_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wj013pgm_cmd.xml
}


FILE FREEFORM = B65CF3E3-325B-4E20-833C-4F89B27B4D2F {
    SECTION UI = "Panel_boe_amoled_wj014sgm_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wj014sgm_cmd.xml
}


FILE FREEFORM = 65C1ECE6-C4F0-49A4-838C-BB2A0A3DF9A8 {
    SECTION UI = "Panel_sdc_amoled_amb127fp01_cmd.xml"
    SECTION RAW = RawFiles/Panel_sdc_amoled_amb127fp01_cmd.xml
}


FILE FREEFORM = F6447E24-AE27-4A2B-9B4A-9FB398087965 {
    SECTION UI = "Panel_sdc_amoled_amb133ha01_cmd.xml"
    SECTION RAW = RawFiles/Panel_sdc_amoled_amb133ha01_cmd.xml
}


FILE FREEFORM = D36B8CDA-DCFD-42B9-A5A2-03CC40EC7CCE {
    SECTION UI = "Panel_sdc_amoled_amb149hb01_cmd.xml"
    SECTION RAW = RawFiles/Panel_sdc_amoled_amb149hb01_cmd.xml
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}


FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
    SECTION UI = "QcomChargerCfg.cfg"
    SECTION RAW = RawFiles/QcomChargerCfg.cfg
}


FILE FREEFORM = F780C779-DD7C-47CD-BD1A-5EB414C51704 {
    SECTION UI = "BATTERY.PROVISION"
    SECTION RAW = RawFiles/BATTERY.PROVISION
}

INF EmbeddedPkg/Ebl/Ebl.inf
